/**
 * Vendors the Noto Emoji PNGs the deco emoji set is ingested from into
 * `sticker-src/noto/`, with the licence, and writes that folder's manifest.
 *
 *   node scripts/stickers/fetch-noto.ts
 *
 * Vendored rather than fetched at ingest so ingest is offline and
 * reproducible, and pinned to a tag so upstream redrawing an emoji can never
 * change stickers already on people's cards. Bump REF deliberately.
 *
 * Licensing, as upstream states it in its README at this tag: "Tools and most
 * image resources are under the Apache license, version 2.0"; the fonts are
 * OFL 1.1. Upstream's root LICENSE file is nevertheless the OFL text, and the
 * Apache notice lives in `svg/LICENSE`, so both are vendored.
 *
 * Console output stays ASCII (cp932 console on the dev machine).
 */

import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';

import { EMOJI_SET, notoFile } from './emoji-set.ts';

const REF = 'v2.047';
const BASE = `https://raw.githubusercontent.com/googlefonts/noto-emoji/${REF}`;
const ROOT = path.resolve(import.meta.dirname, '../..');
const OUT = path.join(ROOT, 'sticker-src/noto');

async function get(file: string): Promise<Buffer> {
	const res = await fetch(`${BASE}/${file}`);
	if (!res.ok) throw new Error(`${file}: HTTP ${res.status}`);
	return Buffer.from(await res.arrayBuffer());
}

mkdirSync(OUT, { recursive: true });

writeFileSync(path.join(OUT, 'LICENSE'), await get('svg/LICENSE'));
writeFileSync(path.join(OUT, 'LICENSE-OFL'), await get('LICENSE'));
writeFileSync(
	path.join(OUT, 'README.md'),
	`# Vendored Noto Emoji artwork

Source: https://github.com/googlefonts/noto-emoji (\`${REF}\`), \`png/512/\`.
Copyright 2013 Google LLC. Upstream's README licenses its image resources under
the Apache License, Version 2.0 (notice in \`LICENSE\`, from upstream
\`svg/LICENSE\`) and its fonts under the SIL OFL 1.1. Upstream's root LICENSE
file at this tag is the OFL text; it is kept as \`LICENSE-OFL\` so nothing is
lost either way.

These are the PNGs \`scripts/stickers/ingest.ts\` bakes the emoji deco stickers
from; the app ships the baked WebPs, not these. The set itself is curated in
\`scripts/stickers/emoji-set.ts\`. Refresh with
\`node scripts/stickers/fetch-noto.ts\`.
`
);

let fetched = 0;
for (const sticker of EMOJI_SET) {
	const file = notoFile(sticker.codepoints);
	const dest = path.join(OUT, file);
	if (existsSync(dest)) continue;
	writeFileSync(dest, await get(`png/512/${file}`));
	console.log(`${sticker.id.padEnd(16)} ${file}`);
	fetched++;
}

const manifest = {
	note: 'Generated by scripts/stickers/fetch-noto.ts from scripts/stickers/emoji-set.ts.',
	stickers: EMOJI_SET.map((s) => ({
		file: notoFile(s.codepoints),
		id: s.id,
		name: s.name,
		kind: 'deco',
		sort_order: s.sort_order,
		source: s.source,
		rarity: 'common'
	}))
};
writeFileSync(path.join(OUT, 'manifest.json'), JSON.stringify(manifest, null, '\t') + '\n');

console.log(
	fetched ? `${fetched} emoji vendored to sticker-src/noto/` : 'sticker-src/noto/ already complete'
);
