/**
 * Copies a handful of baked deco stickers from a dry run into the app as local
 * fixtures, so `/dev/stickers`, the editor's drawer and the Stickers tab can
 * render real sticker art with no Supabase at all.
 *
 *   node scripts/stickers/ingest.ts --dry-run
 *   node scripts/stickers/make-fixtures.ts
 *
 * Files land at `assets/stickers/fixtures/<id>/<hash>-<kind>.webp` — the same
 * relative paths they have in the `stickers` bucket — and
 * `src/stickers/fixtures.generated.ts` maps each path to its `require()`, so
 * `stickerAsset(path)` resolves a fixture exactly as it would a live path.
 */

import { copyFileSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';

import type { IndexEntry } from './ingest.ts';

const ROOT = path.resolve(import.meta.dirname, '../..');
const OUT = path.join(ROOT, 'sticker-out');

/** A spread of shapes and colours: round, spiky, tall, wide, busy, flat. */
const FIXTURE_IDS = [
	'star',
	'heart',
	'sparkles',
	'fire',
	'cat',
	'rocket',
	'crown',
	'dragon',
	'rainbow',
	'pink-heart',
	'ghost',
	'frog',
	'boba',
	'controller'
];

const index: IndexEntry[] = JSON.parse(readFileSync(path.join(OUT, 'index.json'), 'utf8')).stickers;
const chosen = FIXTURE_IDS.map((id) => {
	const entry = index.find((e) => e.id === id);
	if (!entry)
		throw new Error(`${id} is not in sticker-out/index.json; run the ingest dry run first`);
	return entry;
});

const lines: string[] = [];
for (const e of chosen) {
	for (const rel of [e.full_path, e.mask_path, e.thumb_path]) {
		const dest = path.join(ROOT, 'assets/stickers/fixtures', rel);
		mkdirSync(path.dirname(dest), { recursive: true });
		copyFileSync(path.join(OUT, rel), dest);
		lines.push(`\t'${rel}': require('../../assets/stickers/fixtures/${rel}'),`);
	}
}

const stickers = chosen.map((e) => ({
	id: e.id,
	name: e.name,
	kind: 'deco' as const,
	sort_order: e.sort_order,
	source: e.source,
	full_path: e.full_path,
	mask_path: e.mask_path,
	thumb_path: e.thumb_path,
	art_aspect: e.art_aspect
}));

writeFileSync(
	path.join(ROOT, 'src/stickers/fixtures.generated.ts'),
	`// Generated by scripts/stickers/make-fixtures.ts from an ingest dry run. Do not edit.
//
// Baked deco stickers bundled with the app so dev screens and the no-Supabase
// editor can draw real sticker art. Paths match the \`stickers\` bucket's.

export interface FixtureSticker {
\tid: string;
\tname: string;
\tkind: 'deco';
\tsort_order: number;
\tsource: string;
\tfull_path: string;
\tmask_path: string;
\tthumb_path: string;
\tart_aspect: number;
}

export const FIXTURE_STICKERS: FixtureSticker[] = ${JSON.stringify(stickers, null, '\t')};

export const FIXTURE_FILES: Record<string, number> = {
${lines.join('\n')}
};
`
);
console.log(`${chosen.length} fixture stickers -> assets/stickers/fixtures/`);
