// Generated by scripts/stickers/make-fixtures.ts from an ingest dry run. Do not edit.
//
// Baked deco stickers bundled with the app so dev screens and the no-Supabase
// editor can draw real sticker art. Paths match the `stickers` bucket's.

export interface FixtureSticker {
	id: string;
	name: string;
	kind: 'deco';
	sort_order: number;
	source: string;
	full_path: string;
	mask_path: string;
	thumb_path: string;
	art_aspect: number;
}

export const FIXTURE_STICKERS: FixtureSticker[] = [
	{
		id: 'star',
		name: 'Star',
		kind: 'deco',
		sort_order: 10,
		source: 'starter',
		full_path: 'star/419318a559454a45-full.webp',
		mask_path: 'star/419318a559454a45-mask.webp',
		thumb_path: 'star/419318a559454a45-thumb.webp',
		art_aspect: 1.0404
	},
	{
		id: 'heart',
		name: 'Heart',
		kind: 'deco',
		sort_order: 20,
		source: 'starter',
		full_path: 'heart/da7b377662132abd-full.webp',
		mask_path: 'heart/da7b377662132abd-mask.webp',
		thumb_path: 'heart/da7b377662132abd-thumb.webp',
		art_aspect: 1.0764
	},
	{
		id: 'sparkles',
		name: 'Sparkles',
		kind: 'deco',
		sort_order: 30,
		source: 'starter',
		full_path: 'sparkles/d58d3f069fac5fa1-full.webp',
		mask_path: 'sparkles/d58d3f069fac5fa1-mask.webp',
		thumb_path: 'sparkles/d58d3f069fac5fa1-thumb.webp',
		art_aspect: 1.0332
	},
	{
		id: 'fire',
		name: 'Fire',
		kind: 'deco',
		sort_order: 40,
		source: 'starter',
		full_path: 'fire/97f1b6cfc613c562-full.webp',
		mask_path: 'fire/97f1b6cfc613c562-mask.webp',
		thumb_path: 'fire/97f1b6cfc613c562-thumb.webp',
		art_aspect: 0.8142
	},
	{
		id: 'cat',
		name: 'Cat',
		kind: 'deco',
		sort_order: 50,
		source: 'drop',
		full_path: 'cat/84bc5322a1048ca1-full.webp',
		mask_path: 'cat/84bc5322a1048ca1-mask.webp',
		thumb_path: 'cat/84bc5322a1048ca1-thumb.webp',
		art_aspect: 1.1045
	},
	{
		id: 'rocket',
		name: 'Rocket',
		kind: 'deco',
		sort_order: 60,
		source: 'drop',
		full_path: 'rocket/76c700151a058698-full.webp',
		mask_path: 'rocket/76c700151a058698-mask.webp',
		thumb_path: 'rocket/76c700151a058698-thumb.webp',
		art_aspect: 0.9949
	},
	{
		id: 'crown',
		name: 'Crown',
		kind: 'deco',
		sort_order: 90,
		source: 'drop',
		full_path: 'crown/c96ac098ed1239e8-full.webp',
		mask_path: 'crown/c96ac098ed1239e8-mask.webp',
		thumb_path: 'crown/c96ac098ed1239e8-thumb.webp',
		art_aspect: 1.0515
	},
	{
		id: 'dragon',
		name: 'Dragon',
		kind: 'deco',
		sort_order: 100,
		source: 'drop',
		full_path: 'dragon/da6debef60f9442c-full.webp',
		mask_path: 'dragon/da6debef60f9442c-mask.webp',
		thumb_path: 'dragon/da6debef60f9442c-thumb.webp',
		art_aspect: 0.8784
	},
	{
		id: 'rainbow',
		name: 'Rainbow',
		kind: 'deco',
		sort_order: 120,
		source: 'drop',
		full_path: 'rainbow/038ab7ac22ce7364-full.webp',
		mask_path: 'rainbow/038ab7ac22ce7364-mask.webp',
		thumb_path: 'rainbow/038ab7ac22ce7364-thumb.webp',
		art_aspect: 0.9071
	},
	{
		id: 'pink-heart',
		name: 'Pink Heart',
		kind: 'deco',
		sort_order: 130,
		source: 'drop',
		full_path: 'pink-heart/07986ee03a5ba248-full.webp',
		mask_path: 'pink-heart/07986ee03a5ba248-mask.webp',
		thumb_path: 'pink-heart/07986ee03a5ba248-thumb.webp',
		art_aspect: 1.0764
	},
	{
		id: 'ghost',
		name: 'Ghost',
		kind: 'deco',
		sort_order: 260,
		source: 'drop',
		full_path: 'ghost/276902b39ff38cea-full.webp',
		mask_path: 'ghost/276902b39ff38cea-mask.webp',
		thumb_path: 'ghost/276902b39ff38cea-thumb.webp',
		art_aspect: 1.0034
	},
	{
		id: 'frog',
		name: 'Frog',
		kind: 'deco',
		sort_order: 300,
		source: 'drop',
		full_path: 'frog/1d1a332765fe936d-full.webp',
		mask_path: 'frog/1d1a332765fe936d-mask.webp',
		thumb_path: 'frog/1d1a332765fe936d-thumb.webp',
		art_aspect: 1.1298
	},
	{
		id: 'boba',
		name: 'Boba',
		kind: 'deco',
		sort_order: 380,
		source: 'drop',
		full_path: 'boba/166df59625df5117-full.webp',
		mask_path: 'boba/166df59625df5117-mask.webp',
		thumb_path: 'boba/166df59625df5117-thumb.webp',
		art_aspect: 0.6993
	},
	{
		id: 'controller',
		name: 'Controller',
		kind: 'deco',
		sort_order: 410,
		source: 'drop',
		full_path: 'controller/9d997e0ae160fde6-full.webp',
		mask_path: 'controller/9d997e0ae160fde6-mask.webp',
		thumb_path: 'controller/9d997e0ae160fde6-thumb.webp',
		art_aspect: 1.3485
	}
];

export const FIXTURE_FILES: Record<string, number> = {
	'star/419318a559454a45-full.webp': require('../../assets/stickers/fixtures/star/419318a559454a45-full.webp'),
	'star/419318a559454a45-mask.webp': require('../../assets/stickers/fixtures/star/419318a559454a45-mask.webp'),
	'star/419318a559454a45-thumb.webp': require('../../assets/stickers/fixtures/star/419318a559454a45-thumb.webp'),
	'heart/da7b377662132abd-full.webp': require('../../assets/stickers/fixtures/heart/da7b377662132abd-full.webp'),
	'heart/da7b377662132abd-mask.webp': require('../../assets/stickers/fixtures/heart/da7b377662132abd-mask.webp'),
	'heart/da7b377662132abd-thumb.webp': require('../../assets/stickers/fixtures/heart/da7b377662132abd-thumb.webp'),
	'sparkles/d58d3f069fac5fa1-full.webp': require('../../assets/stickers/fixtures/sparkles/d58d3f069fac5fa1-full.webp'),
	'sparkles/d58d3f069fac5fa1-mask.webp': require('../../assets/stickers/fixtures/sparkles/d58d3f069fac5fa1-mask.webp'),
	'sparkles/d58d3f069fac5fa1-thumb.webp': require('../../assets/stickers/fixtures/sparkles/d58d3f069fac5fa1-thumb.webp'),
	'fire/97f1b6cfc613c562-full.webp': require('../../assets/stickers/fixtures/fire/97f1b6cfc613c562-full.webp'),
	'fire/97f1b6cfc613c562-mask.webp': require('../../assets/stickers/fixtures/fire/97f1b6cfc613c562-mask.webp'),
	'fire/97f1b6cfc613c562-thumb.webp': require('../../assets/stickers/fixtures/fire/97f1b6cfc613c562-thumb.webp'),
	'cat/84bc5322a1048ca1-full.webp': require('../../assets/stickers/fixtures/cat/84bc5322a1048ca1-full.webp'),
	'cat/84bc5322a1048ca1-mask.webp': require('../../assets/stickers/fixtures/cat/84bc5322a1048ca1-mask.webp'),
	'cat/84bc5322a1048ca1-thumb.webp': require('../../assets/stickers/fixtures/cat/84bc5322a1048ca1-thumb.webp'),
	'rocket/76c700151a058698-full.webp': require('../../assets/stickers/fixtures/rocket/76c700151a058698-full.webp'),
	'rocket/76c700151a058698-mask.webp': require('../../assets/stickers/fixtures/rocket/76c700151a058698-mask.webp'),
	'rocket/76c700151a058698-thumb.webp': require('../../assets/stickers/fixtures/rocket/76c700151a058698-thumb.webp'),
	'crown/c96ac098ed1239e8-full.webp': require('../../assets/stickers/fixtures/crown/c96ac098ed1239e8-full.webp'),
	'crown/c96ac098ed1239e8-mask.webp': require('../../assets/stickers/fixtures/crown/c96ac098ed1239e8-mask.webp'),
	'crown/c96ac098ed1239e8-thumb.webp': require('../../assets/stickers/fixtures/crown/c96ac098ed1239e8-thumb.webp'),
	'dragon/da6debef60f9442c-full.webp': require('../../assets/stickers/fixtures/dragon/da6debef60f9442c-full.webp'),
	'dragon/da6debef60f9442c-mask.webp': require('../../assets/stickers/fixtures/dragon/da6debef60f9442c-mask.webp'),
	'dragon/da6debef60f9442c-thumb.webp': require('../../assets/stickers/fixtures/dragon/da6debef60f9442c-thumb.webp'),
	'rainbow/038ab7ac22ce7364-full.webp': require('../../assets/stickers/fixtures/rainbow/038ab7ac22ce7364-full.webp'),
	'rainbow/038ab7ac22ce7364-mask.webp': require('../../assets/stickers/fixtures/rainbow/038ab7ac22ce7364-mask.webp'),
	'rainbow/038ab7ac22ce7364-thumb.webp': require('../../assets/stickers/fixtures/rainbow/038ab7ac22ce7364-thumb.webp'),
	'pink-heart/07986ee03a5ba248-full.webp': require('../../assets/stickers/fixtures/pink-heart/07986ee03a5ba248-full.webp'),
	'pink-heart/07986ee03a5ba248-mask.webp': require('../../assets/stickers/fixtures/pink-heart/07986ee03a5ba248-mask.webp'),
	'pink-heart/07986ee03a5ba248-thumb.webp': require('../../assets/stickers/fixtures/pink-heart/07986ee03a5ba248-thumb.webp'),
	'ghost/276902b39ff38cea-full.webp': require('../../assets/stickers/fixtures/ghost/276902b39ff38cea-full.webp'),
	'ghost/276902b39ff38cea-mask.webp': require('../../assets/stickers/fixtures/ghost/276902b39ff38cea-mask.webp'),
	'ghost/276902b39ff38cea-thumb.webp': require('../../assets/stickers/fixtures/ghost/276902b39ff38cea-thumb.webp'),
	'frog/1d1a332765fe936d-full.webp': require('../../assets/stickers/fixtures/frog/1d1a332765fe936d-full.webp'),
	'frog/1d1a332765fe936d-mask.webp': require('../../assets/stickers/fixtures/frog/1d1a332765fe936d-mask.webp'),
	'frog/1d1a332765fe936d-thumb.webp': require('../../assets/stickers/fixtures/frog/1d1a332765fe936d-thumb.webp'),
	'boba/166df59625df5117-full.webp': require('../../assets/stickers/fixtures/boba/166df59625df5117-full.webp'),
	'boba/166df59625df5117-mask.webp': require('../../assets/stickers/fixtures/boba/166df59625df5117-mask.webp'),
	'boba/166df59625df5117-thumb.webp': require('../../assets/stickers/fixtures/boba/166df59625df5117-thumb.webp'),
	'controller/9d997e0ae160fde6-full.webp': require('../../assets/stickers/fixtures/controller/9d997e0ae160fde6-full.webp'),
	'controller/9d997e0ae160fde6-mask.webp': require('../../assets/stickers/fixtures/controller/9d997e0ae160fde6-mask.webp'),
	'controller/9d997e0ae160fde6-thumb.webp': require('../../assets/stickers/fixtures/controller/9d997e0ae160fde6-thumb.webp')
};
