"""
Generate src/card/layout/outfit-metrics.ts from the bundled Outfit TTFs.

    python scripts/make-outfit-metrics.py

Card spec section 9: every "will this fit" decision on the card (name ellipsis,
pronoun pill, link handles, bio line breaks) is driven by real advance widths
and kerning from the exact font files the app ships, not an average character
width. The output is plain data with no React Native imports, so the web card
can import the same file and break lines in exactly the same places.

Needs fontTools (`python -m pip install fonttools`).
"""

from pathlib import Path

from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parent.parent
FONTS = ROOT / "assets" / "fonts"
OUT = ROOT / "src" / "card" / "layout" / "outfit-metrics.ts"

WEIGHTS = {"400": "Outfit-Regular.ttf", "600": "Outfit-SemiBold.ttf", "700": "Outfit-Bold.ttf"}

# ASCII, Latin-1, and the typographic punctuation people actually type into a
# bio or a name (curly quotes, dashes, ellipsis, bullet, middle dot).
CODEPOINTS = (
    list(range(32, 127))
    + list(range(160, 256))
    + [0x2018, 0x2019, 0x201C, 0x201D, 0x2013, 0x2014, 0x2026, 0x2022, 0x00B7, 0x2122]
)


def pair_kerning(font, glyph_to_cp):
    """XAdvance adjustments from GPOS PairPos lookups (formats 1 and 2)."""
    kern = {}
    if "GPOS" not in font:
        return kern
    gpos = font["GPOS"].table
    wanted = set(glyph_to_cp)
    for lookup in gpos.LookupList.Lookup:
        subtables = []
        for st in lookup.SubTable:
            # Extension lookups (type 9) wrap the real subtable.
            if lookup.LookupType == 9:
                if st.ExtensionLookupType != 2:
                    continue
                st = st.ExtSubTable
            elif lookup.LookupType != 2:
                continue
            subtables.append(st)
        for st in subtables:
            firsts = [g for g in st.Coverage.glyphs]
            if st.Format == 1:
                for g1, ps in zip(firsts, st.PairSet):
                    if g1 not in wanted:
                        continue
                    for rec in ps.PairValueRecord:
                        v = getattr(rec.Value1, "XAdvance", 0) if rec.Value1 else 0
                        if v and rec.SecondGlyph in wanted:
                            kern.setdefault((g1, rec.SecondGlyph), v)
            elif st.Format == 2:
                cls1 = st.ClassDef1.classDefs if st.ClassDef1 else {}
                cls2 = st.ClassDef2.classDefs if st.ClassDef2 else {}
                for g1 in firsts:
                    if g1 not in wanted:
                        continue
                    c1 = cls1.get(g1, 0)
                    row = st.Class1Record[c1]
                    for g2 in wanted:
                        c2 = cls2.get(g2, 0)
                        rec = row.Class2Record[c2]
                        v = getattr(rec.Value1, "XAdvance", 0) if rec.Value1 else 0
                        if v:
                            kern.setdefault((g1, g2), v)
    return kern


def metrics_for(path):
    font = TTFont(path)
    upm = font["head"].unitsPerEm
    cmap = font.getBestCmap()
    hmtx = font["hmtx"]
    hhea = font["hhea"]

    advances = {}
    glyph_to_cp = {}
    for cp in CODEPOINTS:
        g = cmap.get(cp)
        if g is None:
            continue
        advances[cp] = round(hmtx[g][0] * 1000 / upm)
        glyph_to_cp.setdefault(g, cp)

    # Kerning only among ASCII and curly quotes: accented Latin-1 letters kern
    # like their base letters to within a unit or two, and carrying every pair
    # would triple the size of a file the app bundles.
    kern_cps = set(range(32, 127)) | {0x2018, 0x2019, 0x201C, 0x201D}
    kern_glyphs = {g: cp for g, cp in glyph_to_cp.items() if cp in kern_cps}
    kern = {}
    for (g1, g2), v in pair_kerning(font, kern_glyphs).items():
        kern[(kern_glyphs[g1], kern_glyphs[g2])] = round(v * 1000 / upm)
    kern = {k: v for k, v in kern.items() if v}

    lower = [advances[c] for c in range(ord("a"), ord("z") + 1)]
    return {
        "ascender": round(hhea.ascent / upm, 4),
        "descender": round(hhea.descent / upm, 4),
        "avg": round(sum(lower) / len(lower)),
        "advances": advances,
        "kern": kern,
    }


def ts_record(pairs):
    return "{ " + ", ".join(f"{k}: {v}" for k, v in pairs) + " }"


def main():
    out = [
        "/**",
        " * Outfit advance widths and kerning, in thousandths of an em.",
        " *",
        " * GENERATED by `python scripts/make-outfit-metrics.py` from the TTFs in",
        " * `assets/fonts`. Do not edit by hand; rerun the script if the fonts change.",
        " *",
        " * Plain data with no React Native imports, so the web card can use the same",
        " * file and make exactly the same fit decisions (card spec section 9).",
        " */",
        "",
        "export interface OutfitMetrics {",
        "\t/** Baseline to the top of the line box, in ems. */",
        "\tascender: number;",
        "\t/** Baseline to the bottom of the line box, in ems (negative). */",
        "\tdescender: number;",
        "\t/** Fallback advance for a Latin character the table does not cover. */",
        "\tavg: number;",
        "\t/** Advance per code point. */",
        "\tadvances: Readonly<Record<number, number>>;",
        "\t/** Pair kerning keyed `left * 65536 + right`. */",
        "\tkern: Readonly<Record<number, number>>;",
        "}",
        "",
    ]
    names = []
    for weight, file in WEIGHTS.items():
        m = metrics_for(FONTS / file)
        name = f"OUTFIT_{weight}"
        names.append((weight, name))
        kern_items = sorted((a * 65536 + b, v) for (a, b), v in m["kern"].items())
        out += [
            f"const {name}: OutfitMetrics = {{",
            f"\tascender: {m['ascender']},",
            f"\tdescender: {m['descender']},",
            f"\tavg: {m['avg']},",
            f"\tadvances: {ts_record(sorted(m['advances'].items()))},",
            f"\tkern: {ts_record(kern_items)}",
            "};",
            "",
        ]
        print(f"Outfit {weight}: {len(m['advances'])} advances, {len(kern_items)} kern pairs")
    out += [
        "export const OUTFIT: Readonly<Record<400 | 600 | 700, OutfitMetrics>> = {",
        ",\n".join(f"\t{w}: {n}" for w, n in names),
        "};",
        "",
    ]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(out), encoding="utf-8", newline="\r\n")
    print(f"wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
